language: java
cache: 

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

sudo: false # faster builds

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)